repos:
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.7
  hooks:
    - id: autopep8
      args: ['--in-place']

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      files: \.py$

- repo: local
  hooks:
    - id: run-tests
      name: Run tests
      entry: pytest
      language: system
      always_run: true
      pass_filenames: false
