name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==3.2.5 astroid==3.2.3
        pip install -r requirements.txt

    - name: Check pylint version
      run: |
        pylint --version

    - name: List files for pylint
      run: |
        find . -name "*.py"

    - name: Run pylint
      id: pylint
      run: |
        pylint --rcfile=.pylintrc **/*.py > pylint_report.txt || true

    - name: Display pylint report
      run: |
        cat pylint_report.txt

    - name: Check pylint score
      id: check_score
      run: |
        score=$(grep 'Your code has been rated at' pylint_report.txt | awk '{print $7}' | cut -d/ -f1)
        echo "Pylint score: $score"
        if (( $(echo "$score > 8.0" | bc -l) )); then
          echo "Pylint check passed"
          exit 0
        else
          echo "Pylint check failed"
          exit 1
        fi
